### PR TITLE
Consistent codes in connector-service (#539)

### LINKED ISSUE #539: Response codes should be consistent in the Connector Service
**Description**

Response codes should be consistent in the Connector Service:

- client-certs endpoint should return 403 on the wrong token
- client-certs endpoint should return 400 on wrong CSR
- messages sent to a user should be more specific and user-friendly. Counterexample: `illegal base64 data at input byte 5`

**Expected result**

- Proper response codes returned
- The acceptance tests updated

### PR DESCRIPTION
**Pull request by Maladie**
**Description**

Changes proposed in this pull request:

- Resolves #539

**Related issue(s)**

### CODE REVIEW

File: components/connector-service/internal/certificates/certificates.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ func (cu *certificateUtility) decodeBytesFromBase64(bytes []byte) (decodedData [
 	data := make([]byte, base64.StdEncoding.DecodedLen(len(bytes)))
 	_, err := base64.StdEncoding.Decode(data, bytes)
 	if err != nil {
-		return nil, apperrors.Internal("Error while decoding base64 bytes: %s", err)
+		return nil, apperrors.Internal("Error while decoding base64 bytes. Internal error from base64 library: %s", err)
```
Comment (janmedrek) [inline components/connector-service/internal/certificates/certificates.go]: 'Internal error from base64 library' does not sound good, perhaps something like 'Invalid base64 string' would be better?

The same goes for latter occurrence in this file and the one in tests

File: docs/application-connector/docs/assets/connectorapi.yaml [hunk 2]
```diff
@@ -97,6 +97,12 @@ paths:
             application/json:
               schema:
                 $ref: '#/components/schemas/csrResponse'
+        '400':
+          description: 'Invalid CSR.'
```
Comment (janmedrek) [inline docs/application-connector/docs/assets/connectorapi.yaml]: The CSR may be actually valid, it just does not meet our subject fields requirements, I would suggest doing something like 'Improper subject values in CSR', you may want to double-check it with @lszymik

File: docs/application-connector/docs/assets/connectorapi.yaml [hunk 3]
```diff
@@ -97,6 +97,12 @@ paths:
...
+            content:
```
Comment (janmedrek) [inline docs/application-connector/docs/assets/connectorapi.yaml]: This indentation is wrong, it should be the on same level as description, you can see the error in Swagger Editor: https://editor.swagger.io/

**Comment by janmedrek** [comment]
Also, please do sign CLA :)
