### PR TITLE
Fix running UI API Layer acceptance tests on local machine

### LINKED ISSUE #1550: Investigate running UI API Layer acceptance tests outside minikube
- [ ] See why UI API Layer acceptance tests fail outside minikube
- [ ] Write acceptance tests for remote environments subscriptions.

Follow up task for:
https://github.com/kyma-project/kyma/pull/1513

### PR DESCRIPTION
**Pull request by jcwiekala**
**Description**

Changes proposed in this pull request:
- Test was updated of remote environment subscription validation,
- Increased timeout from 3 to 10 seconds to prevent **context deadline exceeded** error, which is probably related to authentication request.

**Related issue(s)**
#1550

### CODE REVIEW

File: tests/ui-api-layer-acceptance-tests/k8s/client.go [hunk 1]
```diff
@@ -3,6 +3,7 @@ package k8s
 import (
 	scClientset "github.com/kubernetes-incubator/service-catalog/pkg/client/clientset_generated/clientset"
```
Comment (pkosiec) [inline tests/ui-api-layer-acceptance-tests/k8s/client.go]: In the meantime could you please rename the `k8s` package to `client`? It's definitely confusing to have both `k8s` in `domain` and in `root` folder. Thanks!

File: tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go [hunk 2]
```diff
@@ -61,16 +96,79 @@ func TestRemoteEnvironmentMutations(t *testing.T) {
...
+	req := graphql.NewRequest(query)
+	return c.Subscribe(req)
+}
+
+func remoteEnvironmentEventFields() string {
+	return `
+        remoteEnvironmentEvent {
+			type
+    		remoteEnvironment{
+				name
```
[the remark this answers is not in the document]
Comment (pkosiec) [reply tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go]: Also, please use the function that returns all RE fields in `createRE` and `updateRE` functions. We need to make sure that we query all fields of the type for every operation.

File: tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go [hunk 3]
```diff
@@ -22,64 +36,153 @@ type reDeleteMutation struct {
...
+    		remoteEnvironment{
+				%s
+			}
+        }
+    `, reFields())
+}
+
+func reFields() string {
+	return `
+		name
```
Comment (pkosiec) [inline tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go]: As I wrote before: make sure that you return all fields of RE type. They are defined here: https://github.com/kyma-project/kyma/blob/master/components/ui-api-layer/internal/gqlschema/schema.graphql

File: tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go [hunk 4]
```diff
@@ -22,64 +36,153 @@ type reDeleteMutation struct {
...
+	updateResp, err := updateRE(c, fixedRE)
 	require.NoError(t, err)
-	assert.Equal(t, fixResponse, updateResp.ReUpdateMutation)
+	assert.Equal(t, fixedRE, updateResp.ReUpdateMutation)
 }
 
-func createRE(c *graphql.Client, given reMutationData) (reCreateMutationResponse, error) {
-	query := `
+func createREStruct(name string, desc string, labels map[string]string) remoteEnvironment {
+	return remoteEnvironment{
```
Comment (pkosiec) [inline tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go]: return a pointer

File: tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go [hunk 5]
```diff
@@ -22,64 +36,153 @@ type reDeleteMutation struct {
...
+		`, reEventFields())
+	req := graphql.NewRequest(query)
+	return c.Subscribe(req)
+}
+
+func reEventFields() string {
+	return fmt.Sprintf(`
+        remoteEnvironmentEvent {
+			type
+    		remoteEnvironment{
```
Comment (pkosiec) [inline tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go]: please fix formatting here

File: tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go [hunk 6]
```diff
@@ -3,83 +3,226 @@
...
+	AccessLabel string
 }
 
 type reDeleteMutation struct {
 	Name string `json:"name"`
 }
 
 type reCreateMutationResponse struct {
-	ReCreateMutation reMutationData `json:"createRemoteEnvironment"`
+	ReCreateMutation remoteEnvironment `json:"createRemoteEnvironment"`
```
Comment (pkosiec) [inline tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go]: Wrong type - please use `reMutationOutput` type, which should be equal to previous `reMutationData`

File: tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go [hunk 7]
```diff
@@ -3,83 +3,226 @@
...
 }
 
 type reUpdateMutationResponse struct {
-	ReUpdateMutation reMutationData `json:"updateRemoteEnvironment"`
+	ReUpdateMutation remoteEnvironment `json:"updateRemoteEnvironment"`
```
Comment (pkosiec) [inline tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go]: Wrong type - please use `reMutationOutput` type, which should be equal to previous `reMutationData`

File: tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go (hunk 6 above)
Comment (pkosiec) [reply tests/ui-api-layer-acceptance-tests/domain/remoteenvironment/remoteenvironment_test.go]: See `schema.graphql`:

```
type RemoteEnvironmentMutationOutput {
    name: String!
    description: String!
    labels: Labels!
}
```
