### PR TITLE
Fix for relative path issue in sync-bundles.sh

### LINKED ISSUE #60: Helm Broker is not updated correctly by sync-bundles.sh
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**
After updating content of kyma/resources/helm-broker-repo/bundles directory I want to update repository by executing sync-bundles.sh script from kyma/resources/helm-broker-repo/development directory.

**Expected result**

Repository and index.yaml visible via web server is updated. No error messages are shown.

**Actual result**

"bundles does not exists" error message is shown, repo is not updated.

### PR DESCRIPTION
**Pull request by KarolGrzyb**
Confirm these statements before you submit your pull request:

- [x] I have read and submitted the required [Contributor Licence Agreements](https://github.com/kyma-project/community/blob/master/CONTRIBUTING.md#agreements-and-licenses).
- [x] This pull request follows the contributing guidelines, recommended Git workflow, and templates.
- [x] I have tested my changes.
- [x] I have updated the relevant documentation.
---

**Description**

Executing original script from 'development' directory causes "bundles does not exists" error message - path is resolved relative to 'development' not 'helm-broker-repo'. Repository is not synced correctly because of this.

Changes proposed in this pull request:

Change script to resolve 'bundles' path relative to 'helm-broker-repo' directory.

**Issue link**

Fixes #60

### CODE REVIEW

File: resources/helm-broker-repo/development/sync-bundles.sh [hunk 1]
```diff
@@ -2,10 +2,12 @@
 
 NAMESPACE=kyma-system
 
-PROVISIONING_DIR="$(dirname $0)/../provisioning"
+BASE_DIR="$(dirname $0)/.."
```
Comment (mszostok) [inline resources/helm-broker-repo/development/sync-bundles.sh]: IMO it should not be called a base dir because u go outside of this directory. What's more, this will result in a relative path (https://www.electrictoolbox.com/bash-script-directory/)
because of that in our scripts, we are using the absolute path to make sure that it will always work, see https://github.com/kyma-project/kyma/blob/master/installation/scripts/installer.sh#L5. Please follow this pattern, so it could look like this one:

```bash
#!/usr/bin/env bash

NAMESPACE=kyma-system

readonly CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly PROVISIONING_DIR="${CURRENT_DIR}/../provisioning"
readonly BUNDLES_DIR="${CURRENT_DIR}/../bundles"

bash ${PROVISIONING_DIR}/provision-bundles.sh ${BUNDLES_DIR}

HELM_BROKER_POD_NAME=$(kubectl get po -n ${NAMESPACE} -l app=core-helm-broker -o jsonpath="{.items[0].metadata.name}")

kubectl delete pod ${HELM_BROKER_POD_NAME} -n ${NAMESPACE}

```

**Comment by mszostok** [comment]
Hi @KarolGrzyb, thanks for your contribution!  please see my minor comment, after resolving it I will approve this changes :)

**Comment by KarolGrzyb** [comment]
Hi @mszostok, thanks for the review, I applied and tested your suggestion, it works fine on my env :)
